const enviroment = {
    API_BASE_URL: process.VUE_APP_API_BASE_URL,
    /* FIREBASE */
    FIREBASE_API_KEY: process.env.VUE_APP_FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.VUE_APP_FIREBASE_AUTH_DOMAIN,
    FIREBASE_DATABASE_URL: process.env.VUE_APP_FIREBASE_DATABASE_URL,
    FIREBASE_PROJECT_ID: process.env.VUE_APP_FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.VUE_APP_FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.VUE_APP_FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.VUE_APP_FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.VUE_APP_FIREBASE_MEASUREMENT_ID
};

export default enviroment;
